CREATE TABLE [dbo].[MiTable]
(
[Id] [int] NOT NULL,
[NOm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MiTable] ADD CONSTRAINT [PK_MiTable] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
